[build]
  # nextjs build command
  command = "next build"

  # nextjs output directory   
  publish = ".next" 

  # default ignore command
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."  

[[plugins]]
# netlify nextjs plugin that helps nextjs ISR and SSR and API routes, etc
package = "@netlify/plugin-nextjs"
